apiVersion: v1
kind: Service
metadata:
  name: redmine-service
spec:
  ports:
    - port: 3000
  selector:
    app: redmine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine-deployment
spec:
  selector:
    matchLabels:
      app: redmine
  replicas: 1
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: redmine:latest
          env:
            - name: REDMINE_DB_MYSQL
              value: "mysql-service"
            - name: REDMINE_DB_USERNAME
              value: "root"
            - name: REDMINE_DB_PASSWORD
              value: "password"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: redmine-persistent-storage
              mountPath: /usr/src/redmine/files
      volumes:
        - name: redmine-persistent-storage
          persistentVolumeClaim:
            claimName: redmine-data
